import { PropsWithChildren } from "react";

import "@/app/globals.css";
import { TRPCProvider } from "@/app/providers/TRPCProvider";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
            <body>
                <TRPCProvider>{children}</TRPCProvider>
            </body>
        </html>
    );
}
