name: Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable && corepack install
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn test
        env:
          MONGODB_URI_TESTS: ${{ secrets.MONGODB_URI_TESTS }}
  Deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Enable corepack
        run: corepack enable && corepack install
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Pull Vercel Environment Information
        run: yarn vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: yarn vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}